# Generated by Django 3.2.12 on 2022-05-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Portal', '0005_student_current_year'),
        ('Accounts', '0006_alter_studentfeedetails_fees_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Portal.student')),
                ('studentFeeDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.studentfeedetails')),
            ],
        ),
    ]
