# Generated by Django 3.2.12 on 2022-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdashboard',
            name='loginid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
