# Generated by Django 3.2.12 on 2022-07-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0002_auto_20220611_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdashboard',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
