# Generated by Django 3.2.12 on 2022-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashboard', '0004_auto_20220709_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdashboard',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
