# Generated by Django 4.0.2 on 2022-03-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_studentfeedetails_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedetails',
            name='last_paid_amount',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfeedetails',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
