# Generated by Django 4.0.2 on 2022-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_studentfeedetails_last_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedetails',
            name='fees_paid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
