# Generated by Django 4.0.2 on 2022-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=10)),
                ('year_of_admissn', models.CharField(max_length=4)),
            ],
        ),
    ]
