# Generated by Django 4.0.2 on 2022-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0004_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
